name: Craft challenges
twitter: agilepartner
facebook: agilepartner
github: agilepartner
contact: contact@agilepartner.net
linkedin: agile-partner-s-a-

# Build settings
markdown: kramdown

plugins:
 - github-pages