name: Craft challenges
twitter: https://twitter.com/agilepartner
facebook: https://www.facebook.com/agilepartner
github: https://github.com/agilepartner

# Build settings
markdown: kramdown

plugins:
 - github-pages